export const GET_USERS = "GET_USERS";

export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const ADD_RENT_REQUESTED = "ADD_RENT_REQUESTED";
export const ADD_RENT_SUCCESS = "ADD_RENT_SUCCESS";
export const ADD_RENT_FAILED = "ADD_RENT_FAILED";

export const UPDATE_RENT_REQUESTED = "UPDATE_RENT_REQUESTED";
export const UPDATE_RENT_SUCCESS = "UPDATE_RENT_SUCCESS";
export const UPDATE_RENT_FAILED = "UPDATE_RENT_FAILED";

export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
